# Sample config for Grafana Agent
# For a full configuration reference, see: https://grafana.com/docs/agent/latest/configuration/.
server:
  log_level: warn

metrics:
  global:
    scrape_interval: 1m

  wal_directory: '/var/lib/grafana-agent'
  configs:
    # Example Prometheus scrape configuration to scrape the agent itself for metrics.
    # This is not needed if the agent integration is enabled.
    # - name: agent
    #   host_filter: false
    #   scrape_configs:
    #     - job_name: agent
    #       static_configs:
    #         - targets: ['127.0.0.1:9090']

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true
    include_exporter_metrics: true
    disable_collectors:
      - "mdadm"
  prometheus_remote_write:
    - url: http://load-balancer:9009/api/v1/push
      headers:
        X-Scope-OrgID: demo
  snmp:
    config_file: "/etc/agent/snmp.yaml"
    enabled: true
    snmp_targets:
      - name: synology
        address: my-nas-ip
        module: synology
        walk_params: public
    walk_params:
      public:
        version: 2
        auth:
          community: public

logs:
  configs:
  - name: default
    clients:
      - url: http://load-balancer:3100/loki/api/v1/push
        tenant_id: demo
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: varlogs
        static_configs:
          - targets: [localhost]
            labels:
              job: varlogs
              __path__: /var/log/*.log