{
 "title": "Synology Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Server:", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelName{job=\"integrations/snmp/synology\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "serialNumber{job=\"integrations/snmp/synology\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load5{agent_hostname=\"grafana-agent\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}))"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(node_load15{agent_hostname=\"grafana-agent\"}) * 100) / count(count by(cpu) (node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 / node_memory_MemTotal_bytes{agent_hostname=\"grafana-agent\"}) * (node_memory_MemTotal_bytes{agent_hostname=\"grafana-agent\"} - (node_memory_MemFree_bytes{agent_hostname=\"grafana-agent\"} + node_memory_Cached_bytes{agent_hostname=\"grafana-agent\"} + node_memory_Buffers_bytes{agent_hostname=\"grafana-agent\"} + node_memory_SReclaimable_bytes{agent_hostname=\"grafana-agent\"}))"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{agent_hostname=\"grafana-agent\"} - node_memory_SwapFree_bytes{agent_hostname=\"grafana-agent\"}) / (node_memory_SwapTotal_bytes{agent_hostname=\"grafana-agent\"} )) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{agent_hostname=\"grafana-agent\"} - node_boot_time_seconds{agent_hostname=\"grafana-agent\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{agent_hostname=\"grafana-agent\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{agent_hostname=\"grafana-agent\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "upgradeAvailable{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "version{job=\"integrations/snmp/synology\"}"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "cpuFanStatus{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "systemFanStatus{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "systemStatus{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "powerStatus{job=\"integrations/snmp/synology\"}"
    }
   ]
  },
  {
   "title": "RAID Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidStatus{job=\"integrations/snmp/synology\", raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=\"integrations/snmp/synology\",raidName=\"Volume 1\"}*raidFreeSize{job=\"integrations/snmp/synology\",raidName=\"Volume 1\"})",
     "legendFormat": "Volume 1"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"integrations/snmp/synology\",raidName=\"Volume 2\"}*raidFreeSize{job=\"integrations/snmp/synology\",raidName=\"Volume 2\"})",
     "legendFormat": "Volume 2"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"integrations/snmp/synology\",raidName=\"Volume 3\"}*raidFreeSize{job=\"integrations/snmp/synology\",raidName=\"Volume 3\"})",
     "legendFormat": "Volume 3"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"integrations/snmp/synology\",raidName=\"Volume 4\"}*raidFreeSize{job=\"integrations/snmp/synology\",raidName=\"Volume 4\"})",
     "legendFormat": "Volume 4"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"integrations/snmp/synology\",raidName=\"Volume 5\"}*raidFreeSize{job=\"integrations/snmp/synology\",raidName=\"Volume 5\"})",
     "legendFormat": "Volume 5"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"integrations/snmp/synology\",raidName=\"Volume 6\"}*raidFreeSize{job=\"integrations/snmp/synology\",raidName=\"Volume 6\"})",
     "legendFormat": "Volume 5"
    }
   ]
  },
  {
   "title": "Users / Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "serviceUsers{job=\"integrations/snmp/synology\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Hard Drives",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "diskTemperature{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "diskType{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "diskStatus{job=\"integrations/snmp/synology\"}"
    },
    {
     "expr": "diskModel{job=\"integrations/snmp/synology\"}"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ifPhysAddress{job=\"integrations/snmp/synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    },
    {
     "expr": "ifSpeed{job=\"integrations/snmp/synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    },
    {
     "expr": "ifOperStatus{job=\"integrations/snmp/synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}"
    }
   ]
  },
  { "title": "CPU / RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", agent_hostname=\"grafana-agent\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", agent_hostname=\"grafana-agent\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', agent_hostname=\"grafana-agent\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", agent_hostname=\"grafana-agent\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"idle\", agent_hostname=\"grafana-agent\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{agent_hostname=\"grafana-agent\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{agent_hostname=\"grafana-agent\"} - node_memory_MemFree_bytes{agent_hostname=\"grafana-agent\"} - (node_memory_Cached_bytes{agent_hostname=\"grafana-agent\"} + node_memory_Buffers_bytes{agent_hostname=\"grafana-agent\"} + node_memory_SReclaimable_bytes{agent_hostname=\"grafana-agent\"}))",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{agent_hostname=\"grafana-agent\"} + node_memory_SReclaimable_bytes{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "RAM Free"
    }
   ]
  },
  {
   "title": "SWAP Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "SWAP Total"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{agent_hostname=\"grafana-agent\"} - node_memory_SwapFree_bytes{agent_hostname=\"grafana-agent\"})",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapFree_bytes{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "SWAP Free"
    }
   ]
  },
  { "title": "HDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Disk write io/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sda\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata2\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdb\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata3\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdc\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata4\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdd\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata5\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sde\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata6\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdf\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata7\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdg\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sata8\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"sdh\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"nvme0n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-nvme0"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"nvme1n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-nvme1"
    }
   ]
  },
  {
   "title": "Disk write MB/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sda\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata1"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata2\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdb\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata2"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata3\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdc\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata3"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata4\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdd\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata4"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata5\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sde\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata5"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata6\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdf\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata6"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata7\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdg\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata7"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sata8\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"sdh\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-sata8"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"nvme0n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-nvme0"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=\"nvme1n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "write-nvme1"
    }
   ]
  },
  {
   "title": "Disk read io/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sda\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata2\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdb\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata3\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdc\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata4\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdd\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata5\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sde\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata6\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdf\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata7\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdg\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sata8\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"sdh\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"nvme0n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-nvme0"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"nvme1n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-nvme1"
    }
   ]
  },
  {
   "title": "Disk read MB/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sda\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata1"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata2\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdb\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata2"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata3\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdc\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata3"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata4\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdd\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata4"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata5\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sde\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata5"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata6\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdf\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata6"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata7\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdg\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata7"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sata8\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"sdh\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-sata8"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"nvme0n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-nvme0"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=\"nvme1n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "read-nvme1"
    }
   ]
  },
  {
   "title": "Disk Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sda\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata2\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdb\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata3\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdc\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata4\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdd\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata5\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sde\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata6\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdf\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata7\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdg\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata8\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdh\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme0n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-nvme0"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme1n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-nvme1"
    }
   ]
  },
  {
   "title": "System Disk Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sda\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata2\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdb\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata2"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata3\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdc\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata3"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata4\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdd\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata4"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata5\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sde\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata5"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata6\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdf\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata6"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata7\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdg\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata7"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sata8\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"sdh\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-sata8"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme0n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-nvme0"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=\"nvme1n1\", agent_hostname=\"grafana-agent\"}[$__rate_interval])",
     "legendFormat": "util-nvme1"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Host - Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"integrations/snmp/synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}{{ifName}}"
    }
   ]
  },
  {
   "title": "Host - Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=\"integrations/snmp/synology\", ifName=~\"eth.*|ovs_.*|bond.*\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}{{ifName}}"
    }
   ]
  },
  { "title": "exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Node Exporter - Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{agent_hostname=\"grafana-agent\"}",
     "legendFormat": "{{label_name}}{{collector}}"
    }
   ]
  },
  {
   "title": "SNMP Exporter - Scrape Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{job=\"integrations/snmp/synology\"}",
     "legendFormat": "{{label_name}}{{job}}"
    }
   ]
  }
 ]
}